app = "anaamsayeda25-harbour-ml-solution"

[build]
dockerfile = "Dockerfile.classifier"

[env]
PORT = "8000"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
